apiVersion: v1
kind: Namespace
metadata:
  name: secrets-backup
  labels:
    kubernetes.io/metadata.name: secrets-backup
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
