apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich-postgres-backup.yaml
  - mariadb-backup.yaml
  - redis-backup.yaml
  - age-recipients-mariadb-configmap.yaml
  - age-recipients-redis-configmap.yaml
  - age-recipients-immich-configmap.yaml
