apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-data
  namespace: diun
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 256Mi
