apiVersion: v1
kind: Namespace
metadata:
  name: adguard
  labels:
    kubernetes.io/metadata.name: adguard
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
