apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
  labels:
    kubernetes.io/metadata.name: mariadb
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
