apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/controller: "none"
    traefik.ingress.kubernetes.io/router.middlewares: external-authelia@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - longhorn.homelab.invalid
      secretName: longhorn-tls
  rules:
    - host: longhorn.homelab.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
