apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-target.yaml
  - backup-window-cronjob.yaml
  - encrypted-storageclass.yaml
  - ingress.yaml
  - label-volumes-cronjob.yaml
  - recurring-backup.yaml
