apiVersion: v1
kind: Namespace
metadata:
  name: mumble
  labels:
    kubernetes.io/metadata.name: mumble
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
