apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mumble-data
  namespace: mumble
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 1Gi
