# nix run .#regenerate-manifests
#
# Rewrites the manifests derived from cluster.json and k8s/certs/. Run after
# changing either, commit the result; Flux applies the files, not this app.
#
# Not a configMapGenerator: kustomize's load restrictor is per-directory, so
# k8s/authelia can't reference ../certs/step-ca-root.pem, and fanning one
# ConfigMap into five namespaces needs a component or an operator. Generating
# the five files makes CA rotation "replace the PEM, run this".
{
  pkgs,
  cluster,
  mkApp,
  ...
}:
let
  wg = cluster.wireguard;
  vips = cluster.loadBalancer.vips;
  poolRange = pkgs.lib.splitString "-" cluster.loadBalancer.pool;
  poolStart = builtins.elemAt poolRange 0;
  poolStop = builtins.elemAt poolRange 1;
  registriesCel = pkgs.lib.concatMapStringsSep ", " (r: "\"${r}\"") cluster.allowedRegistries;
  registriesShell = pkgs.lib.concatStringsSep " " cluster.allowedRegistries;
in
mkApp {
  name = "regenerate-manifests";
  runtimeInputs = [ pkgs.coreutils ];
  text = ''
          SRC=k8s/certs/step-ca-root.pem
          [ -s "$SRC" ] || { echo "missing $SRC" >&2; exit 1; }

          n=0
          for f in k8s/*/step-ca-root-configmap.yaml; do
            ns="$(basename "$(dirname "$f")")"
            {
              echo "# GENERATED by \`nix run .#regenerate-manifests\` from k8s/certs/step-ca-root.pem"
              echo "# Do not edit the certificate here - edit the canonical file and re-run."
              echo "apiVersion: v1"
              echo "kind: ConfigMap"
              echo "metadata:"
              echo "  name: step-ca-root"
              echo "  namespace: $ns"
              echo "data:"
              echo "  ca.pem: |"
              sed "s/^/    /" "$SRC"
            } > "$f"
            echo "  wrote $f"
            n=$((n+1))
          done
          echo "$n ConfigMaps regenerated from $SRC"

          # age recipients for the in-cluster backup jobs, from cluster.json so
          # the jobs cannot drift from the recipients the restore path holds.
          # No YubiKey recipients here: encrypting to age1yubikey1 needs the
          # plugin, which alpine does not package. The offline key (password manager)
          # and edenprairie's host key are native age recipients.
          for ns in secrets-backup mariadb redis immich; do
            case "$ns" in
              secrets-backup) f=k8s/secrets-backup/age-recipients-configmap.yaml ;;
              *)              f=k8s/db-backup/age-recipients-$ns-configmap.yaml ;;
            esac
            {
              echo "# GENERATED by \`nix run .#regenerate-manifests\` from cluster.json. Do not edit."
              echo "apiVersion: v1"
              echo "kind: ConfigMap"
              echo "metadata:"
              echo "  name: age-recipients"
              echo "  namespace: $ns"
              echo "data:"
              echo "  recipients: |"
              printf '%s\n' ${
                pkgs.lib.concatMapStringsSep " " (r: "'    ${r}'") cluster.clusterBackupRecipients
              }
            } > "$f"
            echo "  wrote $f"
          done

          # Values mirrored between cluster.json and manifests (DNS names, host
          # IPs, CIDRs, the kube-dns IP); regenerate the fenced regions so they
          # cannot drift. Each fence names its region because one file can
          # carry several. Reusing one name in one file replaces every such
          # region with the SAME content at the same indentation - only do
          # that for genuinely identical blocks.
          splice() { # splice FILE NAME CONTENT
            grep -q "# BEGIN $2:" "$1" || {
              echo "missing marker '$2' in $1" >&2; exit 1;
            }
            # Unbalanced markers would make awk swallow everything from BEGIN to
            # EOF and still exit 0 - a silent truncation, not a splice.
            b=$(grep -c "# BEGIN $2:" "$1")
            e=$(grep -c "# END $2" "$1" || true)
            [ "$b" = "$e" ] || { echo "unbalanced '$2' markers in $1 ($b begin, $e end)" >&2; exit 1; }
            NAME="$2" REPL="$3" awk '
              index($0, "# BEGIN " ENVIRON["NAME"] ":") { print; printf "%s", ENVIRON["REPL"]; skip=1; next }
              index($0, "# END " ENVIRON["NAME"])       { skip=0 }
              !skip { print }
            ' "$1" > "$1.tmp" && mv "$1.tmp" "$1"
            echo "  spliced $1 ($2)"
          }

          ADMIN_NAMES="${
            pkgs.lib.concatStringsSep " " (
              builtins.attrNames cluster.internalServices.devices ++ cluster.internalServices.cluster
            )
          }"
          REWRITES="    # Split-horizon DoT/DoH: LAN clients resolve dnstls to AdGuard's own VIP
        # and connect directly; external clients get the public A record
        # (brainerd, which relays 853/443 through the wg tunnel). Home devices'
        # Private DNS thus never depends on brainerd or the public record.
        - domain: dnstls.homelab.invalid
          answer: ${vips.adguard}
          enabled: true
        # Internal-only admin services, resolve locally to the Traefik VIP
        # instead of leaking hostnames + LAN IPs via public DNS. These names
        # exist only here and in edenprairie dnsmasq, never in the public zone;
        # devices without a local resolver cannot reach them, intended.
    "
          for n in $ADMIN_NAMES; do
            REWRITES="$REWRITES    - domain: $n.homelab.invalid
          answer: ${vips.traefik}
          enabled: true
    "
          done
          for hostip in edenprairie=${cluster.infra.edenprairie} nas=${cluster.infra.nas} \
                        duluth=${cluster.nodes.duluth} bemidji=${cluster.nodes.bemidji} fargo=${cluster.nodes.fargo}; do
            REWRITES="$REWRITES    - domain: ''${hostip%%=*}.lan
          answer: ''${hostip#*=}
          enabled: true
    "
          done
          splice k8s/adguard/AdGuardHome.yaml rewrites "$REWRITES"

          splice k8s/coredns/configmap.yaml forward "      forward . ${cluster.dns}
    "
          splice k8s/cluster-healthcheck/cronjob.yaml podcidr '                  EXPECT_POD_CIDR="${cluster.podCidr}"
    '
          splice k8s/cluster-healthcheck/cronjob.yaml kubedns '                  KUBEDNS_IP="${cluster.kubeDns}"
    '
          splice k8s/cluster-healthcheck/cronjob.yaml nameservers '              - ${cluster.kubeDns} # kube-dns Service (CoreDNS)
                  - ${cluster.dns} # edenprairie dnsmasq - out-of-band fallback
    '
          splice k8s/home-heartbeat/daemonset.yaml targets '              TARGETS="
                  duluth=${cluster.nodes.duluth}
                  bemidji=${cluster.nodes.bemidji}
                  fargo=${cluster.nodes.fargo}
                  edenprairie=${cluster.infra.edenprairie}
                  nas=${cluster.infra.nas}
                  "
    '
          splice k8s/coredns/service.yaml clusterip '  clusterIP: ${cluster.kubeDns}
    '
          splice flux/releases/cilium-values.yaml apiserver 'k8sServiceHost: ${cluster.apiVIP}
    '
          splice flux/releases/cilium-values.yaml podcidr '    clusterPoolIPv4PodCIDRList: ["${cluster.podCidr}"]
    '
          splice flux/releases/traefik-values.yaml trustedips '        - "${cluster.podCidr}"
    '

          # LoadBalancer VIPs and their consumers
          splice k8s/adguard/service.yaml vip '    lbipam.cilium.io/ips: "${vips.adguard}"
    '
          splice k8s/plex/service.yaml vip '    lbipam.cilium.io/ips: "${vips.plex}"
    '
          splice k8s/mumble/service.yaml vip '    lbipam.cilium.io/ips: "${vips.mumble}"
    '
          splice k8s/monitoring/alloy-syslog-service.yaml vip '    lbipam.cilium.io/ips: "${vips.syslog}"
    '
          splice flux/releases/traefik-values.yaml vip '    lbipam.cilium.io/ips: "${vips.traefik}"
    '
          splice flux/releases/loki-values.yaml vip '    loadBalancerIP: "${vips.loki}"
        annotations:
          lbipam.cilium.io/ips: "${vips.loki}"
    '
          splice k8s/cilium/lb-ipam-pool.yaml pool '    - start: ${poolStart}
          stop: ${poolStop}
    '
          splice k8s/wg-gateway/deployment.yaml socat '              socat TCP-LISTEN:443,fork,reuseaddr TCP:${vips.adguard}:443 &
                  socat TCP-LISTEN:853,fork,reuseaddr TCP:${vips.adguard}:853 &
                  socat UDP-LISTEN:853,fork,reuseaddr UDP:${vips.adguard}:853 &
                  socat TCP-LISTEN:64738,fork,reuseaddr TCP:${vips.mumble}:64738 &
                  socat UDP-LISTEN:64738,fork,reuseaddr UDP:${vips.mumble}:64738 &
    '
          splice k8s/plex/deployment.yaml advertise '              value: http://${vips.plex}:32400
    '
          splice k8s/cluster-healthcheck/cronjob.yaml adguardvip '                  value: "${vips.adguard}"
    '
          splice flux/releases/kube-prometheus-stack-values.yaml nodeips '    - ${cluster.nodes.duluth}
        - ${cluster.nodes.bemidji}
        - ${cluster.nodes.fargo}
    '

          # Registry allowlist: the admission policy and the healthcheck must
          # agree, so both come from cluster.json.
          splice k8s/image-admission-policy.yaml registries '      expression: >-
            [${registriesCel}]
    '
          splice k8s/cluster-healthcheck/cronjob.yaml registries '                  ALLOWED_REGISTRIES="${registriesShell}"
    '

          # The wg-gateway conf. Every value here also appears in brainerd's peer
          # block, which reads cluster.json directly, so hand-writing this file lets
          # the two ends of the tunnel drift.
          cat > k8s/wg-gateway/wg-conf.yaml <<EOF
    # GENERATED by \`nix run .#regenerate-manifests\` from cluster.json. Do not edit.
    #
    # Everything in wg0.conf except the private key, which comes from the
    # wg-gateway-key Secret and is set by the first PostUp.
    #
    # The FORWARD allowlist is the security boundary: a compromised brainerd can
    # reach only the VIP:port tuples it already relays publicly, plus Loki. It is
    # enforced here, on the home side, because brainerd's own config cannot be
    # trusted once brainerd is not.
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: wg-gateway-conf
      namespace: wg-gateway
    data:
      wg0.conf: |
        [Interface]
        Address = ${wg.gateway.ip}/24
        # MTU pinned: the node LAN runs jumbo frames and a derived MTU would
        # blackhole large packets on the 1500-MTU WAN path.
        MTU = 1420
        PostUp = wg set %i private-key /etc/wireguard/private.key
        # MASQUERADE: traffic brainerd DNATs into the tunnel leaves via eth0 toward
        # the LB VIPs with the pod as source, so replies return through the pod
        # without routes on other nodes.
        PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        PostUp = iptables -P FORWARD DROP
        PostUp = iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
        PostUp = iptables -A FORWARD -i wg0 -d ${vips.adguard} -p tcp --dport 853 -j ACCEPT
        PostUp = iptables -A FORWARD -i wg0 -d ${vips.adguard} -p udp --dport 853 -j ACCEPT
        PostUp = iptables -A FORWARD -i wg0 -d ${vips.mumble} -p tcp --dport 64738 -j ACCEPT
        PostUp = iptables -A FORWARD -i wg0 -d ${vips.mumble} -p udp --dport 64738 -j ACCEPT
        PostUp = iptables -A FORWARD -i wg0 -d ${vips.loki} -p tcp --dport 3100 -j ACCEPT
        PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

        [Peer]
        PublicKey = ${wg.brainerd.publicKey}
        AllowedIPs = 10.8.0.0/24
        PersistentKeepalive = 25
        # Hostname, not IP: resolved at tunnel-up through the pod's own public
        # resolvers (dnsPolicy: None), so a reprovisioned brainerd with a new
        # address is picked up on the next liveness-probe restart.
        Endpoint = ${cluster.infra.brainerd}:51820
    EOF
          echo "  wrote k8s/wg-gateway/wg-conf.yaml"

          # k8s/external: one Service+Endpoints+Ingress per admin device, all
          # identical except name/title/ip/port - generated so the device list
          # cannot drift from the DNS rewrites above.
          ${pkgs.lib.concatStrings (
            pkgs.lib.mapAttrsToList (name: d: ''
                    cat > k8s/external/${name}.yaml <<'EOF'
              # GENERATED by `nix run .#regenerate-manifests` from cluster.json. Do not edit.
              # ${d.title}
              apiVersion: v1
              kind: Service
              metadata:
                name: ${name}
                namespace: external
              spec:
                ports:
                  - port: ${toString d.port}
                    targetPort: ${toString d.port}
              ---
              apiVersion: v1
              kind: Endpoints
              metadata:
                name: ${name}
                namespace: external
              subsets:
                - addresses:
                    - ip: ${d.ip}
                  ports:
                    - port: ${toString d.port}
              ---
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: ${name}
                namespace: external
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  external-dns.alpha.kubernetes.io/controller: "none"
                  traefik.ingress.kubernetes.io/router.middlewares: external-authelia@kubernetescrd
              spec:
                ingressClassName: traefik
                rules:
                  - host: ${name}.homelab.invalid
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: ${name}
                              port:
                                number: ${toString d.port}
                tls:
                  - hosts:
                      - ${name}.homelab.invalid
                    secretName: ${name}-tls
              EOF
                    echo "  wrote k8s/external/${name}.yaml"
            '') cluster.internalServices.devices
          )}
  '';
}
