# nix run .#ssh-config, LAN mode (default)
# nix run .#ssh-config -- --remote, route the LAN hosts through the
#                                    ssh-home Cloudflare Tunnel
#
# Writes ~/.ssh/config_infra. Idempotent. Add "Include config_infra" to
# ~/.ssh/config once.
#
# The heredoc below is unquoted so $MODE and $PJ expand while the file is
# written; any literal $ or backtick added to the config text must be escaped
# (\$ or \`) or the shell interprets it.
{
  lib,
  cluster,
  mkApp,
}:
let
  # The LAN hosts share one stanza shape; only name and IP differ. $PJ appends
  # "ProxyJump home-jump" to each stanza in --remote mode and is empty in LAN
  # mode.
  lanHosts = {
    duluth = cluster.nodes.duluth;
    bemidji = cluster.nodes.bemidji;
    fargo = cluster.nodes.fargo;
    edenprairie = cluster.infra.edenprairie;
  };
  hostStanza = name: ''

    Host ${name} ${lanHosts.${name}}
        HostName ${lanHosts.${name}}
        User root
        IdentityFile ~/.ssh/id_ed25519_sk_c
        IdentityFile ~/.ssh/id_ed25519_sk_d
        ControlMaster auto
        ControlPath ~/.ssh/cm-%r@%h:%p
        ControlPersist 10m$PJ
  '';
  # Emitted over this list, not attrNames, so the stanzas keep the k8s nodes
  # ahead of the infra hosts in the generated file.
  hostStanzas = lib.concatMapStrings hostStanza [
    "duluth"
    "bemidji"
    "fargo"
    "edenprairie"
  ];
in
mkApp {
  name = "ssh-config";
  runtimeInputs = [ ];
  text = ''
          CONFIG="$HOME/.ssh/config_infra"
          mkdir -p "$HOME/.ssh"

          PJ=""
          MODE="LAN (direct)"
          if [ "''${1:-}" = "--remote" ]; then
            PJ="
        ProxyJump home-jump"
            MODE="REMOTE (via ssh-home tunnel)"
          fi

          cat > "$CONFIG" <<EOF
    # Generated by: nix run .#ssh-config
    # Do not edit manually, re-run the command to update.
    # Mode: $MODE

    # Entry point for REMOTE mode. Harmless in LAN mode, nothing references it
    # unless ProxyJump is emitted below.
    #
    # The token file is separate from cf-brainerd-token because the two Access
    # service tokens are separate: one reaches the edge node, this one reaches home.
    Host home-jump
        HostName ssh-home.homelab.invalid
        User jump
        # Multiplexing is load-bearing, not a speed tweak, the FIDO token serves
        # one request at a time.
        ControlMaster auto
        ControlPath ~/.ssh/cm-%r@%h:%p
        ControlPersist 10m
        IdentityFile ~/.ssh/id_ed25519_sk_c
        IdentityFile ~/.ssh/id_ed25519_sk_d
        StrictHostKeyChecking accept-new
        ProxyCommand /bin/sh -c '. ~/.ssh/cf-home-token && exec /opt/homebrew/bin/cloudflared access ssh --hostname ssh-home.homelab.invalid'
    ${hostStanzas}
    Host nas ${cluster.infra.nas}
        HostName ${cluster.infra.nas}
        Port ${toString cluster.infra.nasSshPort}
        User ${cluster.infra.nasUser}
        IdentityFile ~/.ssh/id_ed25519_sk_c
        IdentityFile ~/.ssh/id_ed25519_sk_d
        KexAlgorithms -mlkem768x25519-sha256$PJ

    Host brainerd ${cluster.infra.brainerd}
        HostName ${cluster.infra.brainerd}
        User root
        IdentityFile ~/.ssh/id_ed25519_sk_c
        IdentityFile ~/.ssh/id_ed25519_sk_d
        StrictHostKeyChecking accept-new
        # Behind Cloudflare Access: without a credential every connection opens a
        # browser, which a script cannot satisfy. ~/.ssh/cf-brainerd-token holds an
        # Access service token; it is a separate mode-600 file because this one is
        # generated 644. Rotate with:
        #   terraform taint cloudflare_zero_trust_access_service_token.brainerd_deploy
        ProxyCommand /bin/sh -c '. ~/.ssh/cf-brainerd-token && exec /opt/homebrew/bin/cloudflared access ssh --hostname ssh-brainerd.homelab.invalid'
    EOF

          echo "Wrote $CONFIG"

          if ! grep -q "Include config_infra" "$HOME/.ssh/config" 2>/dev/null; then
            echo ""
            echo "Add this line to the top of ~/.ssh/config:"
            echo ""
            echo "    Include config_infra"
          fi
  '';
}
